apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-urfhviuv
  janus-idp.io/tekton: go-urfhviuv
  backstage.io/kubernetes-id: go-urfhviuv
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-urfhviuv
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
